### ISSUE TITLE
Is anyone using HES Still!?

### ISSUE THREAD

**Issue by generalwrex** [HellionCommunity/HellionExtendedServer#59]
Comment if you're using it. We're taking a break as no one has left any feedback anywhere!

**Comment by vvzar** [comment]
developer version has unknown bugs with 0.1.10 version: freeze, unresponsive, high memory load, i dont see any errors.
I downgrade to latest master build 20, all works fine.

**Comment by Dprince12** [comment]
I use it for 2 servers. I like being able to see what people are saying in server. So I continue to support you. Hope you keep up with the patch's. Thank you for the program

**Comment by yungtechboy1** [comment]
@Dprince12 Great to hear! I will be starting to push new commits soon.

**Comment by Dprince12** [comment]
@yungtechboy1 Thank you, i cant wait honestly. i just find it so much easier to run a server this way,

**Comment by CheeseJedi** [comment]
Hi - the main website seems to be having certificate issues

"This server could not prove that it is hellionextendedserver.com; its security certificate expired 52 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Wednesday, August 2, 2017. "

**Comment by generalwrex** [comment]
The website is on the list to get back up and running!  Updates to HES are underway!
